language: go
os: osx
go:
  - 1.5

sudo: true

script: "cd file_manager && go test"
script: "ginkgo -noisyPendings=false -progress=true -randomizeAllSpecs=true -r=true"

before_install:
  - export PATH=$GOPATH/bin:$PATH
  - export DATABASE_URL=localhost:28015

before_script:
   - brew update && brew install rethinkdb
   - rethinkdb --daemon
#  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
#  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
#  - sudo apt-get update
#  - sudo apt-get install rethinkdb
