language: go

go:
  - 1.5

sudo: true

script: "cd file_manager && go test"

before_install:
  - export PATH=$GOPATH/bin:$PATH
  - export DATABASE_URL=localhost:28015

before_script:
  - echo "deb http://download.rethinkdb.com/apt precise main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - sudo rethinkdb --bind all &
